### PR TITLE
Fix font used to render symbols in overlay

### LINKED ISSUE #42: macOS: "check" character fails to render
I noticed that the "check" character used to indicate your inventory has all required items rendered inappropriately on macOS (see the attached screenshot).

Image

I can open a PR with an adjustment, however, I see two options, and I’m not sure which of the two is preferred by the maintainers:
1. Use an alternative character that renders well cross-platform.
2. Add an option to overwrite the character in the plugin’s settings.

I can implement either of the options if it’s considered acceptable for the plugin. :)

### PR DESCRIPTION
**Pull request by lukaszklis**
Fixes #42 & #39.

Decided to follow the same approach as the official Clues plugin (https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java#L366-L372), where we adjust the font used to render the right side of the line, and use the same unicode characters for a check mark and the "x".

## Previews (macOS)

**BEFORE:**

Screenshot 2025-05-29 at 21 06 52

**AFTER:**

Screenshot 2025-05-29 at 19 55 17

Sadly, I do not have a Windows machine, nor a Linux one, on which I could test the adjustment.

### CODE REVIEW

File: src/main/java/thestonedturtle/mahoganyhomes/MahoganyHomesOverlay.java [hunk 1]
```diff
@@ -92,17 +96,17 @@ void addMaterialLine(String type, int min, int max, int have)
...
 			{
 				// Player has between max and min, so it's not
 				// certain if they have enough.
-				line = line.right("?").rightColor(Color.YELLOW);
+				line = addLineSuffix(line, "?", Color.YELLOW);
 			}
 			else
 			{
-				line = line.right("x").rightColor(Color.RED);
+				line = addLineSuffix(line, UNICODE_BALLOT_X, Color.RED);
```
Comment (TheStonedTurtle) [inline src/main/java/thestonedturtle/mahoganyhomes/MahoganyHomesOverlay.java:109]: is there a reason we can't just do `line.right(UNICODE_BALLOT_X, Color.red);` instead of creating this new `addLineSuffix` function?

Is `FontManager.getDefaultFont()` required for this to work properly?

Comment (TheStonedTurtle) [reply src/main/java/thestonedturtle/mahoganyhomes/MahoganyHomesOverlay.java:109]: Okay, I wasn't sure if `FontManager.getDefaultFont()` was required for this to work.

I think what you suggested is more readable as regardless of the text we'd want to ensure it renders properly. In the issue even the question mark was rendering weirdly.

Comment (lukaszklis) [reply src/main/java/thestonedturtle/mahoganyhomes/MahoganyHomesOverlay.java:109]: I'll adjust the Pull Request in a few moments then with the more readable approach. 😄
